In [13]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

In [7]:
tf.__version__

'2.19.0'

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [12]:
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [14]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
ann=tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [21]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [22]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 746us/step - accuracy: 0.7747 - loss: 0.5445
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7972 - loss: 0.4620
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.7972 - loss: 0.4459
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - accuracy: 0.7972 - loss: 0.4388
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - accuracy: 0.7972 - loss: 0.4350
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - accuracy: 0.7972 - loss: 0.4321
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.7972 - loss: 0.4298
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.8079 - loss: 0.4275
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.8156 - loss: 0.4250
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - accuracy: 0.8223 - loss: 0.4222
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.8264 - loss: 0.4195
Epoch 12/100
250/25

In [25]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[False]])